### ISSUE TITLE
Impossible to see/add my TV in Home App

### ISSUE THREAD

**Issue by theRansoms** [tavicu/homebridge-samsung-tizen#604] opened 2023-01-17 19:06 UTC
I have my plugin setup and running but cannot add my TV to the Home App, as it does not appear in the "Nearby" section of the Add Accessory dialogue.  If I go to the "My Accessory Isn't Shown Here" section and add the code manually, nothing changes.

If I add my Bridge using the QR Code in HomeBridge it is added to Home App but no device, switches or buttons appear in the App.

**From the HomeBridge Log:**

17/01/2023, 22:46:00Samsung Tizen Bridge starting
17/01/2023, 22:46:10Samsung Tizen BridgeLoaded plugin 'homebridge-samsung-tizen'
17/01/2023, 22:46:10Samsung Tizen BridgeLoading 1 platforms...
17/01/2023, 22:46:10Samsung Tizen BridgeRegistering platform 'homebridge-samsung-tizen.SamsungTizen'
17/01/2023, 22:46:10Samsung Tizen BridgeBridge is running on port 51846.
17/01/2023, 22:46:10Samsung Tizen BridgeLounge TV 553B is running on port 38513.

**My Config file** (it has a bunch of "test" switches and inputs to see how things show up in Home App):

{
    "platform": "SamsungTizen",
    "devices": [
        {
            "name": "Lounge TV",
            "ip": "10.10.21.110",
            "mac": "8c:ea:48:38:c6:f6",
            "switches": [
                {
                    "name": "Mute",
                    "mute": true
                },
                {
                    "name": "Sleep",
                    "sleep": 60
                },
                {
                    "name": "Channel",
                    "channel": 13
                },
                {
                    "name": "Command 1",
                    "command": "KEY_VOLUP"
                },
                {
                    "name": "Command 2",
                    "command": "KEY_VOLUP*5"
                },
                {
                    "name": "Command 3",
                    "command": [
                        "KEY_VOLUP",
                        "KEY_VOLDOWN"
                    ]
                },
                {
                    "name": "Command 4",
                    "command": [
                        "KEY_VOLUP*5",
                        "KEY_VOLDOWN*3"
                    ]
                },
                {
                    "name": "All",
                    "sleep": 60,
                    "mute": true,
                    "command": [
                        "KEY_VOLUP",
                        "KEY_VOLDOWN"
                    ],
                    "channel": 13
                }
            ],
            "inputs": [
                {
                    "name": "My Source",
                    "type": "command",
                    "value": "KEY_SOURCE,KEY_LEFT*3,KEY_ENTER"
                },
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "type": "input",
                    "name": "Live TV",
                    "value": "HDMI1"
                }
            ]
        }
    ]
}

This is an issue that has been previously discussed here however the proposed solution of following the steps in point # 6 on the instructions page doe snot resolve the issue.

I am using iOS 16.1.1 on iPhone 14 Plus to work Home App.  Home Hub is available via multiple devices on my network.

Any new ideas on how to resolve this would be much appreciated.

**Comment by tavicu** [comment] 2023-02-06 08:37
Duplicate of https://github.com/tavicu/homebridge-samsung-tizen/issues/610

**Closed** 2023-02-06 08:37 UTC
