### ISSUE TITLE
The Frame TV Switch Control[Feature] 

### ISSUE THREAD

**Issue by JordanPatterson** [tavicu/homebridge-samsung-tizen#101] opened 2019-05-15 18:28 UTC
Two previous issues have been opened in relation to the Samsung Frame TV. 

[https://github.com/tavicu/homebridge-samsung-tizen/issues/31](url)
[https://github.com/tavicu/homebridge-samsung-tizen/issues/14](url)

I can configure a switch or input to trigger art mode and a true power off.

{"name": "Art Mode", "command": "KEY_POWER"}
{"name": "Power", "command": "KEY_POWER*3s"}

Is there anyway to configure what the main on/off slider does? For example I would love to configure the main power switch to a KEY_POWER*3s command with Art Mode configured as an input.

**Comment by vhardono** [comment] 2019-05-16 02:42
Whenever I toggle main off slider, my Frame TV will turn to Art mode and Homekit will indicate TV in "Off" state.
However after few seconds, the status will revert back to "On" in Homekit although TV still showing Art mode.
@JordanPatterson, do you experience this as well? I'm wondering if this is normal or a bug?

**Comment by JordanPatterson** [comment] 2019-05-16 02:51
> Whenever I toggle main off slider, my Frame TV will turn to Art mode and Homekit will indicate TV in "Off" state.
> However after few seconds, TV status will revert back to "On" in Homekit although TV still showing Art mode.
> @JordanPatterson, do you experience this as well? I'm wondering if this is normal or a bug?

Yes that is the exact behavior I experience. I made an Art Mode input that is a KEY_POWER command, that correct switches to art mode and the tv remains on.

**Comment by tavicu** [comment] 2019-05-17 18:16
I will look and try to implement a method where you can set the command for power off key so you can set it to KEY_POWER*3s to work with frame tv

**Comment by JordanPatterson** [comment] 2019-05-17 18:25
It would also be really cool to keep the power behavior as it is but create some sort of delay so on the frame TV when you hit power it doesn’t update the button/state for a few seconds so it would enter art mode and the TV would remain on.

**Comment by codyc1515** [comment] 2019-05-19 08:05
I have recently purchased one of the Samsung Frame TV and noticed this issue. Someone please correct me if I am wrong in my below analysis.

This plugin infers the TVs switch state, either On or Off, based on its reachability via. TCP/IP. When the TV is in Art Mode it is actually displaying an app and thus is reachable. Thus, this way of checking TV state does not work with the Frame TV's (it will appear to be On when Art Mode is active).

The only time the plugin state shows as Off is when the TV is manually turned off via. the remote. Suffice to say, these issues cause the switch to indicate incorrectly.

There are probably a number of ways to sort this, but the simplest one that comes to mind is checking if the TV is On via. the existing method (should return On), then a further check of the running app = Frame app (in which case it should return Off as the state).

**Comment by tavicu** [comment] 2019-05-20 07:04
I was thinking of that but unfortunately it's a no go if we want to keep the background refresh option.

Why? Because samsung api is stupid and if you make too many requests it will stop responding.

When i wrote the code for v3 first i tried to get the status by calling the websocket instead of looking if the IP is alive. After some time the TV stops responding to requests and you will have to hard reset it to make it work.

So right now the only option to help in order with Frame TV is to allow customizable keys for power on and off. This will allow setting the power off to press the key for 3 seconds and turn the tv off, not in the frame state.

Other option is to disable the background refresh for frame tv's but i don't like it!

**Comment by tavicu** [comment] 2019-05-20 07:06
@JordanPatterson if you have we can test it if it will work changing it to *3s.

Edit the file `/lib/remote.js` from the plugin on line `236`

From this: `await this.api.clickKey('KEY_POWER');`
To this: `await this.api.clickKey('KEY_POWER*3s');`

And let me know if it works as intended.

**Comment by JordanPatterson** [comment] 2019-05-21 04:21
What folder is that file in?

**Comment by tavicu** [comment] 2019-05-21 06:43
Depending where your npm install global packages.

Default it's `/usr/local/lib/node_modules/homebridge-samsung-tizen`

**Comment by nestorix1343** [comment] 2019-05-23 18:33
The KEY_POWER*3s does power off The Frame when used in a switch. However, changing that line 236 did not work. I tried changing it to `await this.api.holdKey("KEY_POWER",3000);` and this worked.

**Comment by tavicu** [comment] 2019-05-24 06:18
Yup, my bad :D it should have been like you said!

I will think at a method and implement today!

**Comment by tavicu** [comment] 2019-05-24 13:19
I have added a feature in the following version.

If your TV is Frame it will automatically use `KEY_POWER*3s` to power it off.

Someone mentioned earlier that when the Frame TV is in frame mode there is an app that will act as active.

If that is true and if someone help me identify that app i can automatically push it to the Inputs.
So this way you will have the option to turn ON/OFF the tv from the main switch and also enter in the frame mode from inputs :)

**Comment by codyc1515** [comment] 2019-05-25 07:33
I don't think this solution really works.

The default behaviour and intent of the Frame TVs is that when you press the power button it goes to Art Mode. However, if you so desire you can hold the power button in for 3 seconds and it fully turns off. The whole purpose of this TV, as opposed to other TVs, is that it displays Art Mode when it is switched off. So to change the On / Off behaviour that will display in this plugin effectively serves to make the Art Mode worthless.

However, I can see why sometimes you may decide to want to turn your TV off fully. Can I suggest that we please make this option to toggle in the device config:

1. Pressing Off turns TV off, but Art Mode becomes available as an input choice
2. Pressing Off goes into Art Mode (the default behaviour)

I have also run the `tizen-apps` command, however, it does not identify any Art Mode app per se. I believe that it is identified using web socket commands as per issue [#50](https://github.com/tavicu/homebridge-samsung-tizen/issues/50#issuecomment-459995170).

**Comment by tavicu** [comment] 2019-05-25 09:10
If you or someone else are willing to help me make some debugs in order to understand how the Frame works and responds to API i will invest some time (a lot ...) to find the best possible way of working for Frames.

Let me know and if you do want to help me, i will prepare a file to run

**Comment by codyc1515** [comment] 2019-05-25 09:18
More than happy to help in any way I can. I have developed HomeBridge plugins for some other devices I am using so am reasonably familiar with the API.

To get the status of the Art Mode send a web socket query, with below body, to: ws://{IPADDR}:8001/api/v2/channels/com.samsung.art-app?name=bruh

{
    "method":"ms.channel.emit",
    "params":{
        "clientIp":"172.16.32.51",
        "data":"{
            \"request\":\"get_artmode_status\",
            \"id\":\"30852acd-1b7d-4496-8bef-53e1178fa839\"
        }",
        "deviceName":"bruh==",
        "event":"art_app_request",
        "to":"host"
    }
}

It should give a response back like the below (artmode_status = on):

{"data":"{\"id\":\"30852acd-1b7d-4496-8bef-53e1178fa839\",\"event\":\"artmode_status\",\"value\":\"on\",\"target_client_id\":\"4b9e510-fa74-49d4-ab36-74aaf27ee46e\"}","event":"d2d_service_message","from":"ba24192-27da-418d-aad0-9a4bccbd8ff6"}

**Comment by tavicu** [comment] 2019-05-25 09:46
Ok. First create a folder and inside of it create an `index.js` file with this content: https://pastebin.com/9yYBEFrx

Then with command line/terminal go to that folder and install ws with `npm install ws`
Make sure your TV is on and run `node index.js TV_IP`. Example: `node index.js 192.168.1.1`
Click allow on TV and the program will run for 10 seconds.

Let me know the outcome :)

**Comment by codyc1515** [comment] 2019-05-25 10:09
Cool. See results here: https://gist.github.com/codyc1515/ed78697652630ef08cbbf18dd8704522

Note that I had to change your code slightly as it didn't work without changes. It has to do with the way the `data` param is sent to the TV. It needs to be encapsulated. You will see in the gist file anyway.

**Comment by tavicu** [comment] 2019-05-25 10:22
Awesome! We are making progress!

1. Are you sure the code it's not working with data as it was? I am asking this because when the request is sent, JSON.stringify is used. Both versions have the same result after JSON.stringify!
2. You changed the timeout. It takes a lot to respond or you just wanted to have larger gaps so you can see the actions?
3. I don't like that we need to change to com.samsung.art-app. This means i will have to keep two sockets opened :(
4. Can you also try to use websocket secure with com.samsung.art-app? Like this `wss://${ip}:8002/api/v2/channels/com.samsung.art-app?name=RnJhbWUgVGVzdA==`

**Comment by codyc1515** [comment] 2019-05-25 10:30
Hey

1. I tried the original code you provided but it gave an error because the `params` `data` was not escaped. It must be escaped or the TV returns an error message. It seems to be decoding this messaging data separately.
2. Timeout is not really relevant but helped me to keep the messages in order for readability, especially so if we are using the callbacks provided by the web socket.
3. I am not sure what the impact is of having the two web sockets open (performance?). However this is required for the request to work. The calls do not respond on the samsung.remote.control interface unfortunately. No idea why Samsung designed it this way.
4. Also not relevant. There are no issues with the secure web sockets. I don't recall exactly why I changed this, but it was probably because the channel had not been changed.

Cheers

**Comment by tavicu** [comment] 2019-05-25 11:16
1. Cool. Will escape it :) Can you try like this please? It should work :)
```
{
    method : 'ms.channel.emit',
    params : {
        data  : JSON.stringify({
            value: 'on',
            request: 'set_artmode_status',
            id: '545fc0c1-bd9b-48f5-8444-02f9c519aaec'
        }),
        to    : 'host',
        event : 'art_app_request'
    }
}
```
3. Performance! But it will also be cool because we keep an socket open and i've seen that it emits an event every time the art mode change! So instead of checking the TV at an interval, i will be able to just listen for the event and change the switch when the event is triggered.

4. I want to go with secure websocket for 'future proof' implementation. A while ago Samsung dumped ws and allowed only wss! There is a chance they will do the same with this api.

**Comment by codyc1515** [comment] 2019-05-25 11:27
I was wondering if placing the stringify there may work... and it does! The rest looks good too. 👍

**Comment by tavicu** [comment] 2019-05-25 11:57
Nice! I have created a new branch and soon i will create a PR where we can keep talking!

Ofc if you are willing to help :)

**Comment by JordanPatterson** [comment] 2019-05-25 14:12
My lack of development skills really showed up, I am glad Cody stepped in. Just as a side note it’s amazing to watch the open source software process work. Bravo, I can’t wait to play with this update.

**Comment by tavicu** [comment] 2019-05-26 14:07
I will close this issue and continue the conversation regarding this over here: #108

**Closed** 2019-05-26 14:07 UTC
Labels: enhancement

**Comment by platini76** [comment] 2021-01-06 18:10
> await this.api.clickKey('KEY_POWER')

I have not this key in all file... there is any news?

**Comment by tavicu** [comment] 2021-03-10 12:25
For anyone wanting to continue discussing and helping implement the Frame support, follow #318
