### ISSUE TITLE
 Frame TV issue: Randomly turns off when on Apple TV input (and possibly other inputs)…

### ISSUE THREAD

**Issue by jplusrco** [tavicu/homebridge-samsung-tizen#489] opened 2022-03-08 02:21 UTC
I was reading through the closed issues forum and came across [filmoreracer’s](https://github.com/tavicu/homebridge-samsung-tizen/issues/428) issue from October 2021. Something about his issue resonated with me because it is happening to me.

I have a 2019 Samsung Frame and Apple TV 4K. While I am interested in a persistent Art Mode (as opposed to an power off state), I’ve worked around this issue by setting an automation in HomeKit which works IF Samsung Frame is powered off, THEN trigger Art Mode Input (which is created via this plugin).

My issue however, is the same as Filmoreracer in that with this plugin installed, periodically, when I watch Apple TV, art mode will be triggered, taking me out of whatever video/app I am watching. This cannot be a Samsung Frame issue because when I turn the plugin off, I no longer have the TV randomly “turn off” (more specifically, turning on Art Mode).

The forum in that thread believed this to be a Samsung issue—not a plugin issue, but I believe that dilemma only refers to an idea of a “persistent art mode”.

I believe there is some sort of bug that is causing the Samsung Frame to randomly trigger Art Mode when this plugin is turned on. Any thoughts or ideas?

**Comment by jplusrco** [comment] 2022-03-08 02:26
Btw, I confirmed this is not an Apple TV issue as my Nintendo Switch also randomly turns to Art Mode when this plugin is turned on. I don’t know if there is a timing to this (i.e. Does this happen every 10 min?) as I haven’t checked. But if I have a chance, I’ll try to look into that as well.

**Comment by tavicu** [comment] 2022-03-08 09:08
First you should start the server in debug mode and see the logs when this happens.

Second, what you are trying to do (your automation) it's not ok. Because when the TV turns off you send command to turn on! Why turning it off in the first time if you don't want that?

From what i know on the frames you could do this only manually by holding the power button. HDMI CEC or just sending the turn off command will set it to Art Mode, not actually power it off!

**Comment by jplusrco** [comment] 2022-03-08 13:46
@tavicu thanks for the response. I will look at the logs and see what's going on.

As for your comment re: automation. There does not seem to be a better way to do this from what we are working with. Here's what a normal behavior in my household is like: 
- Watch something via an app on Apple TV.
- Turn TV to Art Mode when finished, using Samsung Frame remote.

Here's what sometimes happens:
- Watch something via an app on Apple TV
- Get interrupted in the middle or at end of a movie/show and TV displays pause state or the Apple TV menu while waiting for next action.
- At some point Apple TV goes to sleep automatically, triggering HDMI CEC to communicate with the Samsung Frame to go to sleep/turn off.

My desired outcome is to literally always have my Samsung Frame go into Art mode when it "turns off". This works when the TV is physically "powered off" by pressing the Samsung Frame power button, but NOT when it goes to sleep on its own.

As an aside, This is the reason for my automation. Unless you are suggesting this is the culprit of my issue (random change of state to Art Mode while actively playing video), the automation should not really be the main discussion for my problem here. If there's another way to accomplish my desired outcome without using the automation, I'm all ears, but this automation is the only thing I've found that works thus far.

I will look at the logs, but my central concern still remains: What is causing the random changing to Art Mode on Samsung Frame while watching videos on a connected Apple TV?

**Comment by tavicu** [comment] 2022-03-08 13:52
> If there's another way to accomplish my desired outcome without using the automation, I'm all ears, but this automation is the only thing I've found that works thus far.

Disabling HDMI CEC :)
If you ask me the problem over here is on Samsung part because getting the turn off command from HDMI CEC should not actually turn off the tv, it should switch to art mode (or how you configure your TV to do when pressing power button on remote).

> I will look at the logs, but my central concern still remains: What is causing the random changing to Art Mode on Samsung Frame while watching videos on a connected Apple TV?

It looks like at some point the plugin see your TV as off and it triggers the automation.

**Comment by jplusrco** [comment] 2022-03-08 13:55
> It looks like at some point the plugin see your TV as off and it triggers the automation.

It's a good theory. However, this issue existed prior to me adding the automation and also after disabling it.

**Comment by tavicu** [comment] 2022-03-08 13:57
Strange. The plugin should never change the state of TV without interaction (user or automation).

Your best bet is to start homebridge in debug mode and look in the console when the problem is replicated.
That way we can see what commands are sent to TV or what changes are we get on the frame api.

**Comment by jplusrco** [comment] 2022-03-08 13:58
I'll investigate and get back to you. Thanks for your concern and responses.

**Comment by tavicu** [comment] 2022-03-31 07:44
Hei.

I will close the issue now and if you have new informations and debug log please open a new issue and will see what we can do.

Thank you

**Closed by tavicu** 2022-03-31 07:44 UTC
