### ISSUE TITLE
FrameTV implementation On/Off Bug

### ISSUE THREAD

**Issue by CGDaveMac** [tavicu/homebridge-samsung-tizen#324] opened 2021-03-18 14:57 UTC
New issue to branch from https://github.com/tavicu/homebridge-samsung-tizen/issues/318 for debugging.

#318 

> I am getting very consistent results with the TV turning on and the next time the TV is queried via API, the accessory changes to Off in HomeKit. I am hoping I am describing it correctly. (Was considering taking a video.) From that point, when I toggle the accessory switch to ON, the TV then goes to Art Mode and the switch toggles On and then Off again. At that point things are in sync, and it's repeatable.

I don't think I'm explaining what's going on correctly, so a video might help: (Winter scene is Art Mode. When TV is ON, it's HDMI Input with a screensaver playing.)
 https://youtu.be/6okjHY0ZThw

When the accessory switch changes from On to Off in the Home app, there are NO logs generated.

**Comment by tavicu** [comment] 2021-03-18 17:55
Hei! Do you have other plugins/accessories set on the same homebridge instance?

I've seen on mine a strange thing, when i have other plugins (nest for example) and they do something, the websocket is paused somehow and don't receive messages.

Another thing that i find it strange is that when TV switch from art mode to anything it should display the menu bar, like you press home button. But on your TV nothing is shown!

Other than that i can only do some debug on the function that get the status and try to see what returns wrong then dig deeper.

Can you also show me your config file? I don't think i've seen it.

Right now i did the same setup, removed the cable TV and connected only a HDMI input (an apple tv) which is in wallpaper mode.

I am 98% that is a setting from the TV since you don't see the bar with apps when you switch to HDMI.

**Comment by CGDaveMac** [comment] 2021-03-18 19:32
I noticed that there are different firmware versions/downloads for FrameTV sizes. Is there anything different in the TV output / power detection you are using in the API call to make Homebridge see the TV as off when the data is returned?  I looked at the code but would really need to understand it better to see how the power state is interpreted.

**Comment by CGDaveMac** [comment] 2021-03-18 19:40
> I've seen on mine a strange thing, when i have other plugins (nest for example) and they do something, the websocket is paused somehow and don't receive messages.

I am watching the logs come in on http://192.168.7.201:8001/logs/ and the HomeKit accessory turns off immediately after HomeKit queries the TV and it responds. The query and response logs appear every 5 seconds and there is no interruption, s so I believe the websocket is connected.

**Comment by tavicu** [comment] 2021-03-18 20:10
> I think I turned off the home menu on power. We don't use any of the apps on the TV. Just an AppleTV on HDMI input.

Can you guide me to this setting? I’m trying to set everything like you have and see if i can reproduce!



> I looked at the code but would really need to understand it better to see how the power state is interpreted.

there are 3 steps:
1. Ping the IP (if ping don’t respond then stop and return accessory off)
2. Ping responded so we make request to /api/v2 and chech PoweState value! If powerstate != on stop and return accessory off!
3. PowerState was on then check art mode status! If artmode is on then return accessory off!
4. At this state everything was true and accessory shoud be on!


On your video something strange happens and we need to figure out why! When it’s in hdmi mode it reports as OFF, so one of the checks is failing! 

Tomorrow i will work and finish the Power Swich! After that i will make a version for you with more debugs on this part and see what is failing!

**Comment by CGDaveMac** [comment] 2021-03-18 21:00
> Can you guide me to this setting? I’m trying to set everything like you have and see if i can reproduce!
General - Smart Features - Autorun Smart Hub
I turned it on and its unchanged, then turned it back off.

One question, after resetting everything yesterday (I even deleted homebridge bridge from Apple HomeKit and re-added all my devices, I  updated the plugin to the beta version and then ran `npm install https://github.com/tavicu/homebridge-samsung-tizen.git#debug` but I'm not getting the same debug artmode logs in the homebridge console. I do see them directly from the TV though.

**Comment by ucsbricks** [comment] 2021-03-19 17:37
If you like, I can do some testing on my 2018 Frame too. It also has an inconsistent status of the power state related to art mode.

**Comment by tavicu** [comment] 2021-03-21 11:13
Pushed a new beta `v5.0.0-beta.1`

Add the `debug` and `refresh` attributes like this.

```
"devices": [
    {
        "name": "FRM TV",
        "ip": "192.168.10.230",
        "mac": "4C:C9:5E:94:39:BC",
        "refresh": 2000,
        "debug": true
    }
],
```


After that in your console you should see something like this:
```
active-ping true
active-http true
active-art true
active-final true 
```

Follow up the console when you toggle the TV on and see what response with false so the switch goes back to off. Maybe it will help us make an ideea

**Comment by CGDaveMac** [comment] 2021-03-21 14:13
Looks like active-http always returns false:

```
[3/21/2021, 10:06:02 AM] [Living Room TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_POWER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
active-ping true
active-http false
active-ping true
active-http false
active-ping true
active-http false
active-ping true
active-http false
active-ping true
```

**Comment by tavicu** [comment] 2021-03-21 14:39
Active http get `api/v2/` and check powerstate ... hmmm

Ok, we have more info! I will make some things to see if request is failing or powerstate is different

**Comment by CGDaveMac** [comment] 2021-03-21 15:00
Also noticing that there are consistent error in updating HomeKit status, could it be due to the refresh being set to 2000?Looks like it goes away when set to 3000:

```
[3/21/2021, 10:41:45 AM] [Living Room TV] Opening handshake has timed out
[3/21/2021, 10:41:45 AM] [Living Room TV] [DEBUG] SocketOpenError: Opening handshake has timed out
    at WebSocketSecure._check (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:108:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processTimers (internal/timers.js:494:9)
    at WebSocketSecure._send (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:75:9)
    at WebSocketSecure.setActiveOn (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/base.js:83:13)
    at Remote.setActive (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:103:24)
active-ping true
active-http false
```

**Comment by tavicu** [comment] 2021-03-21 15:13
> Also noticing that there are consistent error in updating HomeKit status, could it be due to the refresh being set to 2000?Looks like it goes away when set to 3000:

Nope. That socket is used only to send commands. Failed to open means your TV is off or responds veeeery hard.

**Comment by CGDaveMac** [comment] 2021-03-21 15:21
Should I perhaps start from scratch or reset anything to get a better baseline? 

In your instructions a few time you mentioned that when homebridge starts after resetting the Samsung-tizen.json file, it will ask for permissions. I never got that message. Only shows up when toggling the accessory in Home app.

**Comment by tavicu** [comment] 2021-03-21 15:48
> Should I perhaps start from scratch or reset anything to get a better baseline?
> 
> In your instructions a few time you mentioned that when homebridge starts after resetting the Samsung-tizen.json file, it will ask for permissions. I never got that message. Only shows up when toggling the accessory in Home app.

After starting the homebridge server in 15 seconds should try to pair with your tv if you remove samsung-tizen.json. just like you would send a command.

But this has nothing to do with the status of TV, so let's take it step by step :)

**Comment by CGDaveMac** [comment] 2021-03-21 15:56
Ok, just wondering why things don't seem right.. the new beta didn't expose the power switch for me. I'll standby to see what the next step is.

**Comment by town3r** [comment] 2021-03-21 20:04
What does it mean if I get `true` for all of them if I'm actively watching something say via input HDMI?

More specifically `active-art true`

```
active-ping true
active-http true
active-art true
active-final true 
```

**Comment by tavicu** [comment] 2021-03-21 20:43
> What does it mean if I get `true` for all of them if I'm actively watching something say via input HDMI?
> 
> More specifically `active-art true`

It’s ok cause the status is reversed! So if the art mode is off, the value should be true and if it’s on the value should be false!

The value represents the state of the accessory, not the state of the art mode :)

**Comment by tavicu** [comment] 2021-03-21 20:47
> Ok, just wondering why things don't seem right.. the new beta didn't expose the power switch for me. I'll standby to see what the next step is.

If you removed the json file you need to start the homebridge server again! I still have to make some improvements so the switch will be added after the plugin fetch infos regarding to TV! Right now it looks at the settings saved when you start homebridge server and if the TV is new or the jaon was removes there are no settings saved and don’t know that is a Frame to add the switches!

**Comment by CGDaveMac** [comment] 2021-03-21 22:18
Ok, I have restarted the server many times for all the troubleshooting and understand that well. Is it the because There is no active-http response then?

**Comment by tavicu** [comment] 2021-03-21 22:36
> Ok, I have restarted the server many times for all the troubleshooting and understand that well. Is it the because There is no active-http response then?

Yup! It can be! Because the plugin see if the TV is frame from api/v2/ response!

i’m starting to suspect that is something in your network or your TV responds harder to requests! Especially that you posted the error with opening websocket! If you are comfortable with editing some files i can guide you to change the timeout and see if something changes! Let me know

**Comment by CGDaveMac** [comment] 2021-03-21 22:39
Yes, I would. I looked at the code to if I could determine what was going on, but it's too unfamiliar to me. 

I have left the TV wired to try to solve this and eliminate variables.

**Comment by town3r** [comment] 2021-03-21 22:46
@CGDaveMac Are you able to control the TV successfully via the SmartThings app?

Do you get a response from:

http://tv-ip-address:8001/api/v2/

**Comment by CGDaveMac** [comment] 2021-03-21 23:07
Yep: 

`{"device":{"FrameTVSupport":"true","GamePadSupport":"true","ImeSyncedSupport":"true","Language":"en_US","OS":"Tizen","PowerState":"on","TokenAuthSupport":"true","VoiceSupport":"true","WallScreenRatio":"0","WallService":"false","countryCode":"US","description":"Samsung DTV RCR","developerIP":"192.168.7.204","developerMode":"1","duid":"uuid:1abc165a-49d4-4ff8-9cb6-1d7f7b07aaf4","firmwareVersion":"Unknown","id":"uuid:1abc165a-49d4-4ff8-9cb6-1d7f7b07aaf4","ip":"192.168.7.201","model":"20_NIKEM_FRAME","modelName":"QN43LS03TAFXZA","name":"[TV] Living Room TV","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:1abc165a-49d4-4ff8-9cb6-1d7f7b07aaf4","wifiMac":"bc:7e:8b:3e:5f:24"},"id":"uuid:1abc165a-49d4-4ff8-9cb6-1d7f7b07aaf4","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Living Room TV","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.7.201:8001/api/v2/","version":"2.0.25"}`

**Comment by CGDaveMac** [comment] 2021-03-21 23:14
> > Ok, I have restarted the server many times for all the troubleshooting and understand that well. Is it the because There is no active-http response then?
> 
> Yup! It can be! Because the plugin see if the TV is frame from api/v2/ response!
> 
> i’m starting to suspect that is something in your network or your TV responds harder to requests! Especially that you posted the error with opening websocket! If you are comfortable with editing some files i can guide you to change the timeout and see if something changes! Let me know

I just tried adding timeout: 10000 to my config.json and it appears to be working.

**Comment by CGDaveMac** [comment] 2021-03-21 23:43
Timeout of 1000 fails, but 1500 works.

**Comment by tavicu** [comment] 2021-03-22 09:07
homebridge-samsung-tizen/lib/methods/base.js : Function at line 65 change it to:
```
    getActiveHttp() {
        return this.getInfo().then(data => {
            console.log('getInfo - data', data);
            if (data.device && data.device.PowerState) {
                return data.device.PowerState == 'on';
            }

            return true;
        })
        .catch((error) => {
            console.log('getInfo - error', error)
            return false;
        });
    }
```

It's starting to look like all the problems are because your TV responds very slow. Let's make the change above and see what's happen. Also, don't change the timeout to see exactly what is failing.

If indeed the TV responds very hard i don't know what we could do. Maybe a reset of the TV, but i don't know for sure if it will help.

I will also add one more option for socket timeout. But changing this will take longer for status to update and you will not be able to set refresh intervals too low.

Let's see what the change tells us.

Same steps to do, watch the console when you toggle the TV

**Comment by tavicu** [comment] 2021-03-22 14:25
@CGDaveMac do not update to `v5.0.0-beta.2` yet cause i removed all debug "feature".

Make the change above and we will see after that

**Comment by CGDaveMac** [comment] 2021-03-22 15:17
Ok. I will be able to test this in a few hours.

**Comment by CGDaveMac** [comment] 2021-03-22 20:44
Ok, so after I made the change, I restarted Homebridge and saw a couple things in the console:
`[Living Room TV Power@Living Room TV Power@On] The read handler for the characteristic 'On' was slow to respond!`
As well as:
```
[3/22/2021, 4:29:33 PM] [Living Room TV] Opening handshake has timed out
[3/22/2021, 4:29:33 PM] [Living Room TV] [DEBUG] SocketOpenError: Opening handshake has timed out
    at Frame._check (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:108:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processTimers (node:internal/timers:497:9)
    at Frame._send (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:75:9)
    at Frame.setActiveOn (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/base.js:83:13)
    at Frame.setActiveOn (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/methods/frame.js:38:9)
    at Remote.setActive (/Users/dave/.npm-packages/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:103:24)
```

However, I waited a few minutes and everything stabilized. Now I get the following messages and it behaves exactly as before... as shown in the above video with no extra errors. Here are the logs:

```
active-ping true
active-http false
active-final false 

active-final false 

active-final false 

[3/22/2021, 4:40:37 PM] [Living Room TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_POWER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[3/22/2021, 4:40:37 PM] [Living Room TV] [DEBUG] { value: 'off', request: 'set_artmode_status' }
[3/22/2021, 4:40:39 PM] [Living Room TV] [DEBUG] {
  data: '{\n  "event": "art_mode_changed",\n  "status": "on"\n}',
  event: 'd2d_service_message',
  from: 'd2536d8-4769-4910-b0ff-b3b3b2c43b7d'
}
[3/22/2021, 4:40:39 PM] [Living Room TV] [DEBUG] {
  data: '{\n' +
    '  "event": "image_selected",\n' +
    '  "content_id": "SAM-S2202",\n' +
    '  "matte_id": "modernthin_polar",\n' +
    '  "is_shown": "Yes"\n' +
    '}',
  event: 'd2d_service_message',
  from: 'd2536d8-4769-4910-b0ff-b3b3b2c43b7d'
}
[3/22/2021, 4:40:39 PM] [Living Room TV] [DEBUG] {
  data: '{\n  "event": "art_mode_changed",\n  "status": "on"\n}',
  event: 'd2d_service_message',
  from: 'd2536d8-4769-4910-b0ff-b3b3b2c43b7d'
}
active-ping true
active-http false
active-final false 

active-final false 

active-ping true
active-http false
active-final false 
```

**Comment by CGDaveMac** [comment] 2021-03-22 21:05
Ok, I think I may have misunderstood, do I need to re-compile the file or rebuild node_modules after making changes to base.js?

**Comment by CGDaveMac** [comment] 2021-03-22 21:28
Sorry, I added some comments but then realized I need to do ` npm install -g ./homebridge-samsung-tizen`

Here is the error thrown after each api call:
```
active-ping true
getInfo - error FetchError: network timeout at: http://192.168.7.147:8001/api/v2/
    at Timeout.<anonymous> (/Users/dave/node_modules/node-fetch/lib/index.js:1454:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'request-timeout'
}
active-http false
active-final false 

active-final false 

active-ping true
active-http false
active-final false 
```

**Comment by tavicu** [comment] 2021-03-22 22:15
Ok! So the problem is indeed that the TV responds very slow to requests!

At this point we can check how slow but this will only be a comparison!

I would try resetting the TV to factory! I know is not a nice thing but in 3 years since i made the plugin you are the first with this problem! I’m going blind :)

Another solution is to increase the timeout setting like you already did! But this will throw warnings and will not be very stable!

Something is wrong on your TV for the slow response. Maybe too many apps installed, i really don’t know what to say! Tomorrow i will check how fast my TVs responds so we have some data to compare!

But before resetting the TV or do anything else wait for my reply tomorrow and i will give more instructions so we can see if the TV responds slow indeed  or is something with the Homebridge that slows the requests!

**Comment by CGDaveMac** [comment] 2021-03-22 22:24
My TV is only a couple months old, and I have not install any apps. I only use HDMI. I have downloaded some custom artwork, but that's it. Going to apps page, it says 600MB (15%) available. Maybe due to this issue? https://us.community.samsung.com/t5/Qled-and-Frame/2020-Frame-TV-out-of-space-after-4-pictures/td-p/1367937

 It's a 43" Frame from Costco, and searching the issues I think I saw some other problems people had. 

I was doing some research on node-fetch and it seems with 3.0 the timeout function will be gone. Will this change how you have to make requests to the TV once it's released: https://nicedoc.io/bitinn/node-fetch/docs/v3-UPGRADE-GUIDE.md

I tried a bunch of timeouts and anything below 1000 fails, seems 1050 and above works. I don't see any errors and the TV response is with no warnings or errors.

I appreciate the time spend on this.

**Comment by tavicu** [comment] 2021-03-23 09:18
> Going to apps page, it says 600MB (15%) available. Maybe due to these issues? 

I don't think so, i have less than that.

![IMG_1640](https://user-images.githubusercontent.com/172068/112122094-9a194700-8bc8-11eb-9833-94536e6c452b.jpeg)

> I was doing some research on node-fetch and it seems with 3.0 the timeout function will be gone. Will this change how you have to make requests to the TV once it's released: https://nicedoc.io/bitinn/node-fetch/docs/v3-UPGRADE-GUIDE.md

Nice. I was not aware of that. I will update the code to use the new implementation for timeout.

> I tried a bunch of timeouts and anything below 1000 fails, seems 1050 and above works. I don't see any errors and the TV response is with no warnings or errors.

Ok, let's do some things to see if something is different.

First make sure you update to the latest beta so everything will be clean.

Then go to this file: /homebridge-samsung-tizen/lib/methods/base.js and edit function at line 102 to look like this:
```
    getInfo() {
        let now = Date.now();
        return fetch(`http://${this.ip}:8001/api/v2/`, {
            timeout: 3000
        })
        .then(body => body.json())
        .then(response => {
            console.log('getInfo - time', Date.now() - now);
            return response;
        });
    }
```

Now just restart the homebridge and in the console you should see this:
```
getInfo - time 7
getInfo - time 5
getInfo - time 5
getInfo - time 4
getInfo - time 5
getInfo - time 6
getInfo - time 7
getInfo - time 3
getInfo - time 5
getInfo - time 4
```

This is the time in milliseconds. My TV takes ~6ms to respond.

After that open a terminal and run this command: `curl -o /dev/null -s -w 'Total: %{time_total}s\n' 'http://192.168.10.230:8001/api/v2/'` (ofc replacing the IP).

This should print something like this: 
```
Octavians-iMac:$ curl -o /dev/null -s -w 'Total: %{time_total}s\n' 'http://192.168.10.230:8001/api/v2/'
Total: 0.004054s
Octavians-iMac:$ curl -o /dev/null -s -w 'Total: %{time_total}s\n' 'http://192.168.10.230:8001/api/v2/'
Total: 0.003707s
Octavians-iMac:$ curl -o /dev/null -s -w 'Total: %{time_total}s\n' 'http://192.168.10.230:8001/api/v2/'
Total: 0.003963s
Octavians-iMac:$ curl -o /dev/null -s -w 'Total: %{time_total}s\n' 'http://192.168.10.230:8001/api/v2/'
Total: 0.005121s
```

So as you can see it's also ~5 milliseconds response, same as the plugin.

Let's see what the results are on your end :)

**Comment by CGDaveMac** [comment] 2021-03-23 13:22
getInfo - time 1010
getInfo - time 1011
getInfo - time 1006
getInfo - time 1010
getInfo - time 1012
getInfo - time 1008
getInfo - time 1016
getInfo - time 1009
getInfo - time 1012
getInfo - time 1007
getInfo - time 1008
getInfo - time 1008
getInfo - time 1007

console command results:
Total: 0.019194s
Total: 0.071937s
Total: 0.009607s
Total: 0.013342s
Total: 0.009993s
Total: 0.009835s

**Comment by tavicu** [comment] 2021-03-23 15:51
Ok! So now we know for sure that the TV responds very slow from the terminal, so i won’t call it a problem from the homebridge.

i would also try to run the curl command from different devices if you have. That way we know for sure it’s the TV and not the device you are running homebridge from.

so if you have a pc (terminal on mac and command prompt on windows), tablet or phone (install a ssh app)

if the results are the same ... you should see what you can do on the TV side (resetting, anything it came to your mind and think it will help). If the results are not ok and it responds faster (like mine) then the problem is with your hardware (pi or what you are running from), software or hardware from the network port/wifi

**Comment by town3r** [comment] 2021-03-23 17:07
I'd be curious to know how the TV is currently connected to your network.

Direct via Ethernet or via WiFi?

If via WiFi are you able to see if connecting it via Ethernet helps?

Also WiFi signal strength & age of route / WiFi modes ie: 802.11n, 802.11ac, 802.11ax

If Ethernet, maybe try a different cable / make sure it's cat5 or cat6.

¯\_(ツ)_/¯ just some ideas

**Comment by CGDaveMac** [comment] 2021-03-23 17:12
Up until yesterday, I connected ethernet to eliminate problems, but response is the same as on Wifi so I think I have eliminated that as the problem, unless it's Eero hardware.

But am I reading the results incorrectly? Seems HomeKit reporting 1000ms and curl command 9-19 ms. I am about to try another computer.

**Comment by CGDaveMac** [comment] 2021-03-23 17:19
Forgot mac was on wifi, so just connected it to ethernet:
Total: 0.006698s
Total: 0.013421s
Total: 0.009439s
Total: 0.008687s
Total: 0.011473s
Total: 0.010970s
Total: 0.013296s
Total: 0.008715s
Total: 0.008773s

Homebridge still reporting > 1000.

**Comment by tavicu** [comment] 2021-03-23 17:25
> Seems HomeKit reporting 1000ms and curl command 9-19 ms. 
Yup, it is a big difference between homebridge (~1s) and curl but is still a lot (one of them being 0.071937s)

What i can do is making a small script only with the request using node-fetch and another one method. This way we can see if we get closer to the curl command and the problem is from homebridge/node or it’s because of node-fetch. Give me 15 minutes :)

**Comment by tavicu** [comment] 2021-03-23 17:50
Uploaded to wetransfer: https://we.tl/t-3l2ixdTB0N

Unzip then with your terminal `cd` to folder and run `node index.js 192.168.10.209` (replace ip)
Example of response of one of my TVs:
```
Octavians-MBP:test-request$ node index.js 192.168.10.209
fetch - time 20ms
fetch - time 59ms
fetch - time 14ms
fetch - time 11ms
fetch - time 36ms
fetch - time 11ms
fetch - time 15ms
fetch - time 22ms
fetch - time 9ms
fetch - time 88ms
------
http - time 38ms
http - time 20ms
http - time 7ms
http - time 9ms
http - time 35ms
http - time 9ms
http - time 7ms
http - time 11ms
http - time 8ms
http - time 7ms
```

Fetch is using node-fetch (just like the plugin) and http is request from Node core.

**Comment by CGDaveMac** [comment] 2021-03-23 18:05
```
fetch - time 27ms
fetch - time 11ms
fetch - time 9ms
fetch - time 8ms
fetch - time 11ms
fetch - time 15ms
fetch - time 7ms
fetch - time 7ms
fetch - time 9ms
fetch - time 9ms
------
http - time 10ms
http - time 21ms
http - time 5ms
http - time 7ms
http - time 7ms
http - time 12ms
http - time 11ms
http - time 7ms
http - time 7ms
http - time 8ms

```

**Comment by tavicu** [comment] 2021-03-23 18:09
I want to swear so hard right now ... :))

It’s the exact same code as in the plugin ... don’t understand why running from homebridge takes more than 1000ms ...

**Comment by CGDaveMac** [comment] 2021-03-23 19:07
So, this means it's HomeBridge? That's what I was beginning to think before this test.

Since installing Homebridge years ago, I have kept the same config.json, but have changed the way HomeBridge is launched. I am researching options, don't really want to wipe out my setup.  Maybe another way to refresh/update settings? Possibly create a new homebridge instance to test?

If it's just me, I feel bad for the time spent troubleshooting, but if it is something that can affect more users I am happy to help determine the cause. 

I also disabled all eero advanced DNS features and HomeKit accessory security

**Comment by town3r** [comment] 2021-03-23 19:26
Could look at setting it up on a child bridge.

Might help with the speed.

https://github.com/homebridge/homebridge/wiki/Child-Bridges

**Comment by CGDaveMac** [comment] 2021-03-23 19:33
I tried that last week, obviously before the debug code, but it made no difference.

**Comment by town3r** [comment] 2021-03-23 19:38
What's homebridge running on?
Are you rocking a Raspberry Pi?
Is it responsible for running lots of other things or is homebridge it's main purpose?￼

**Comment by CGDaveMac** [comment] 2021-03-23 19:42
It's on an 2017 Retina 5K iMac.

**Comment by tavicu** [comment] 2021-03-23 19:42
> If it's just me, I feel bad for the time spent troubleshooting, but if it is something that can affect more users I am happy to help determine the cause.

Don’t need to feel bad :) 

You are the first one that reports this problem!
You could try setting a homebridge server on another pc (maybe you mac) without hb-service and see the results!

npm install -g homebridge
npm install -g homebridge-samsung-tizen@beta
Create the config file ~/.homebridge/config.json only with the TV

Then start the homebridge and see the result!

Don’t know how you set your instances and on what device you run the server but me for example i use a Raspberry Pi with [docker-homebridge](https://github.com/oznu/docker-homebridge) and i have multiple instances to not crowd an instance!
Running this setup since ~3 years ago without problems!

**Comment by town3r** [comment] 2021-03-23 20:15
I was just gonna recommend looking into a cheap little raspberry pi.

I had it running on this little $10 guy.
https://vilros.com/collections/raspberry-pi-zero/products/raspberry-pi-zero-w

Although I've got one of these
https://vilros.com/products/vilros-raspberry-pi-4-complete-starter-kit-with-fan-cooled-heavy-duty-aluminum-alloy-case?variant=31893966684254

Running the homebridge raspbian os and is super easy to set up.
https://github.com/homebridge/homebridge-raspbian-image

It's also running PiHole and acting as my DNS and DHCP server.

**Comment by CGDaveMac** [comment] 2021-03-24 00:39
> > If it's just me, I feel bad for the time spent troubleshooting, but if it is something that can affect more users I am happy to help determine the cause.

> npm install -g homebridge
> npm install -g homebridge-samsung-tizen@beta
> Create the config file ~/.homebridge/config.json only with the TV
> 
> Then start the homebridge and see the result!

So... "good" news? I did this on an OLDER mac and I am getting 8-15 ms. So something is definitely wrong with homebridge setup on my mac. Guess I need to figure out how to start fresh.

**Comment by tavicu** [comment] 2021-03-24 07:29
> So... "good" news? I did this on an OLDER mac and I am getting 8-15 ms. So something is definitely wrong with homebridge setup on my mac. Guess I need to figure out how to start fresh.

i’m happy to hear that cause if was the TV I didn’t know what you could do 🥳

**Comment by tavicu** [comment] 2021-03-29 09:39
Ok, as we found out what it was and there is nothing more we can do, i will close the issue :)

**Closed by tavicu** 2021-03-29 09:39 UTC
