### ISSUE TITLE
Custom Commands Don’t Work with Config UI X

### ISSUE THREAD

**Issue by jianyu-li** [tavicu/homebridge-samsung-tizen#311] opened 2021-02-24 03:15 UTC
I can get the commands to work when editing the config file manually but if I do anything in config ui x it either deletes the commands or puts the wrong commands in the config

**Comment by tavicu** [comment] 2021-03-04 11:23
Hi, i tried and everything is set correctly. Nothing was removed.

Can you tell me the exact steps you made?

**Comment by jianyu-li** [comment] 2021-03-05 00:26
> Hi, i tried and everything is set correctly. Nothing was removed.
> 
> Can you tell me the exact steps you made?

So I have custom commands in the config file. Then I go to “inputs” and go to add an input and “Apple TV” is there but not the custom command. When I paste in the custom command, it comes over into the config file like this: “\”KEY_SOURCE\”. 

Here is what I am pasting 
"KEY_SOURCE",
                                "KEY_LEFT*4",
                                "KEY_RIGHT*3",
                                "KEY_ENTER"
                                
And here are the screens
![B3CFF602-EC0A-4E93-BF34-7AA612492E00](https://user-images.githubusercontent.com/52750081/110049249-57b9c400-7d06-11eb-8102-6ea246a35906.jpeg)
![7628AD46-EC61-4A00-9CAE-35BCF1836B6C](https://user-images.githubusercontent.com/52750081/110049252-58eaf100-7d06-11eb-985e-eec40e0c7a7c.jpeg)
![C4AA712E-30AD-4F68-8CEB-88C06D6A69C7](https://user-images.githubusercontent.com/52750081/110049253-5a1c1e00-7d06-11eb-9820-7685b1370ba7.jpeg)

**Comment by tavicu** [comment] 2021-03-05 20:30
Hei @jianyu-li, i have found the problem and i will push a new version tomorrow which will allow you to set a list of commands.

The problem is that the interface don't support to have the same input with two types. It can be string or array, but not both.
And in the configuration panel is set as string. If you edit your `config.json` and add as array, when you will save the settings from the settings interface will remove your value.

The version i am pushing will not resolve this problem but will allow you to send a string of commands separated by comma like this: `KEY_SOURCE,KEY_LEFT*4,KEY_RIGHT*3,KEY_ENTER`

**Comment by jianyu-li** [comment] 2021-03-05 20:41
> Hei @jianyu-li, i have found the problem and i will push a new version tomorrow which will allow you to set a list of commands.
> 
> 
> 
> The problem is that the interface don't support to have the same input with two types. It can be string or array, but not both.
> 
> And in the configuration panel is set as string. If you edit your `config.json` and add as array, when you will save the settings from the settings interface will remove your value.
> 
> 
> 
> The version i am pushing will not resolve this problem but will allow you to send a string of commands separated by comma like this: `KEY_SOURCE,KEY_LEFT*4,KEY_RIGHT*3,KEY_ENTER`

Thank you!!

**Comment by tavicu** [comment] 2021-03-07 18:42
I have pushed the changes but not release a new version yet cause i made more changes and i would like to test the new version for a few days before releasing to public.

I will update you when the new version will be released

**Comment by jianyu-li** [comment] 2021-03-07 21:30
@tavicu  appreciate it

**Comment by tavicu** [comment] 2021-03-10 08:20
Hei @jianyu-li , i have pushed the new version. Now for Inputs you can set it as a list of commands separated by comma.
For example: `KEY_SOURCE,KEY_LEFT*4,KEY_RIGHT*3,KEY_ENTER`

**Closed by tavicu** 2021-03-10 08:20 UTC
Labels: bug

**Comment by jianyu-li** [comment] 2021-03-10 14:56
@tavicu  great! Looks like there's some other good things in this update as well! Thanks! I'll drop a donation later today

**Comment by tavicu** [comment] 2021-03-10 14:59
> @tavicu great! Looks like there's some other good things in this update as well! Thanks! I'll drop a donation later today

Thank you very much! I appreciate it :)

I had some free days so i was able to work more on the plugin and implement features that makes sense and help us all.

**Comment by MarkBarbieri** [comment] 2021-06-15 00:19
> The problem is that the interface don't support to have the same input with two types. It can be string or array, but not both.
> And in the configuration panel is set as string.

@tavicu, this comment makes sense.  Just a thought to extend on your fix here which might cater for this case.

https://github.com/tavicu/homebridge-samsung-tizen/commit/0c5f6dd39c13f30fcd301658a940a195b620cc4f

If the command is an array, and the array length is 1, try and split the first array value by ','.  In this way, a string entered in the UI like "KEY_SOURCE,KEY_LEFT\*4,KEY_RIGHT\*3,KEY_ENTER" will still work.  This is also much easier to enter multiple commands in the UI (on 1 line instead of multiple)

(Untested)
```
        if (!Array.isArray(commands)) {
              // Remove spaces and split after comma            
              commands = commands.replace(/\s/g, '').split(',');        
        } else {
              if (Array.isArray(commands) && commands.length === 1) {
                     // Remove spaces and split after comma
                    commands = commands[0].replace(/\s/g, '').split(',');        
              }
       }
```

**Comment by tavicu** [comment] 2021-06-15 06:44
Hi. There is no reason to do this :)

Also i consider the array implementation deprecated. It's there just to be backward compatible. But all the wikis are updated to the string version :)

**Comment by MarkBarbieri** [comment] 2021-06-15 09:25
That’s fine, but schema still says array of strings, so even when I start with a new config it creates an array

https://github.com/tavicu/homebridge-samsung-tizen/blob/6ce2de1923fcbed4346280865ed441597a68a872/config.schema.json#L50

Does the schema need an update?

**Comment by tavicu** [comment] 2021-06-15 09:28
Hei, yes. For switches i didn't update the wiki & schema yet :) Only for inputs.

It's been a very buys period for me at work so i didn't had time to do anything regarding the wiki. My next step is to update all the pages once i will have a few days off

**Comment by MarkBarbieri** [comment] 2021-06-15 09:37
No problem at all, just something I stumbled across and thought I’d pass it on.   It’s not causing me an issue, but it will for someone at some stage.  

Thanks for all your great work

**Comment by tavicu** [comment] 2021-06-15 09:40
Yup, that's why i didn't want to change it yet! Because i will need to be more vocal about the release and make the things clear.

Cause once i switch the array to string everybody that have the config with array and will update the settings through Config Ui interface will loose the value since in config it's array and config.schema will be string and can't convert array to string, so it will be blank :)
